name: bo-front build and release

on:
  push:
    tags: [ 'v*.*', 'v*.*.*' ]

defaults:
  run:
    working-directory: bo-front/

env:
  COMPONENT: bo-front

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Get repository name
      id: repository
      run: echo "::set-output name=pathref::$(echo '${{ github.repository }}' | cut -d'/' -f2)-${{ env.COMPONENT }}-$(echo '${{ github.ref_name }}' | sed 's/[^[:alnum:]\.]/_/g')"

    - name: create artifact archive
      run: |
        mv ./build '${{ steps.repository.outputs.pathref }}'
        tar -zcf build.tar.gz '${{ steps.repository.outputs.pathref }}'

    - name: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      id: create_release
      with:
        draft: false
        prerelease: false
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ${{ env.COMPONENT }} release ${{ github.ref }}

    - name: upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.COMPONENT }}/build.tar.gz
        asset_name: '${{ steps.repository.outputs.pathref }}.tar.gz'
        asset_content_type: application/gzip
