name: fo-private build and release

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*.*', 'v*.*.*' ]
    paths:
      - 'fo-private/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'fo-private/**'

defaults:
  run:
    working-directory: fo-private/

env:
  COMPONENT: fo-private

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Get repository name
      id: repository
      run: echo "::set-output name=pathref::$(echo '${{ github.repository }}' | cut -d'/' -f2)-${{ env.COMPONENT }}-$(echo '${{ github.ref_name }}' | sed 's/[^[:alnum:]\.]/_/g')"

    - name: create artifact archive
      run: |
        mv ./build '${{ steps.repository.outputs.pathref }}'
        tar -zcf '${{ steps.repository.outputs.pathref }}.tar.gz' '${{ steps.repository.outputs.pathref }}'

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.COMPONENT }}/${{ steps.repository.outputs.pathref }}.tar.gz
        fail_on_unmatched_files: true
      if: startsWith(github.ref, 'refs/tags/')
