name: oxe-api PyCQA Prospector

on:
  push:
    branches: [ 'main', 'validation' ]
    tags: [ 'v*.*', 'v*.*.*' ]
    paths:
      - 'oxe-api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'oxe-api/**'

defaults:
  run:
    working-directory: oxe-api/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run PyCQA Prospector
        run: |
          prospector -i venv/ --no-autodetect
